import {
  FaCalculator,
  FaChartBar,
  FaFileAlt,
  FaDatabase,
  FaBrain,
  FaNewspaper,
  FaGlobe,
  FaFlask,
  FaUsers,
  FaComments,
  FaUserTie,
  FaCogs,
  FaIndustry,
  FaMicrochip,
  FaVial,
  FaCode,
  FaJava,
  FaLaptopCode,
  FaNetworkWired,
  FaServer,
  FaMicroscope,
  FaDna,
  FaAtom,
  FaFlask as FaFlaskAlt,
  FaPuzzlePiece,
  FaQuestionCircle,
  FaFont,
  FaClock,
} from "react-icons/fa";

export const categoriesData = [
  {
    title: "General Aptitude",
    icon: FaCalculator,
    color: "#ef5350",
    items: [
      {
        name: "Arithmetic Aptitude",
        icon: FaCalculator,
        topics: "35 Topics",
        path: "/general-aptitude/arithmetic-aptitude",
        progress: 15,
      },
      {
        name: "Data Interpretation",
        icon: FaChartBar,
        topics: "4 Topics",
        path: "/general-aptitude/data-interpretation",
        progress: 4,
      },
      {
        name: "Online Aptitude Test",
        icon: FaFileAlt,
        topics: "10 Tests",
        path: "/general-aptitude/online-aptitude-test",
        progress: 10,
      },
      {
        name: "Data Interpretation Test",
        icon: FaDatabase,
        topics: "10 Tests",
        path: "/general-aptitude/data-interpretation-test",
        progress: 10,
      },
    ],
  },
  {
    title: "Verbal and Reasoning",
    icon: FaBrain,
    color: "#7e57c2",
    items: [
      {
        name: "Verbal Ability",
        icon: FaBrain,
        topics: "19 Topics",
        path: "/verbal-and-reasoning/verbal-ability",
        progress: 19,
      },
      {
        name: "Logical Reasoning",
        icon: FaBrain,
        topics: "19 Topics",
        path: "/verbal-and-reasoning/logical-reasoning",
        progress: 19,
      },
      {
        name: "Verbal Reasoning",
        icon: FaBrain,
        topics: "16 Topics",
        path: "/verbal-and-reasoning/verbal-reasoning",
        progress: 14,
      },
      {
        name: "Non Verbal Reasoning",
        icon: FaBrain,
        topics: "17 Topics",
        path: "/verbal-and-reasoning/non-verbal-reasoning",
        progress: 17,
      },
    ],
  },
  {
    title: "Current Affairs & GK",
    icon: FaNewspaper,
    color: "#4caf50",
    items: [
      {
        name: "Current Affairs",
        icon: FaNewspaper,
        topics: "40 Questions",
        path: "/current-affairs-gk/current-affairs",
        progress: 0,
      },
      {
        name: "Basic General Knowledge",
        icon: FaGlobe,
        topics: "35 Questions",
        path: "/current-affairs-gk/basic-general-knowledge",
        progress: 0,
      },
      {
        name: "General Science",
        icon: FaFlask,
        topics: "40 Questions",
        path: "/current-affairs-gk/general-science",
        progress: 0,
      },
      {
        name: "Read more...",
        icon: FaFileAlt,
        topics: "30 Questions",
        path: "/current-affairs-gk/read-more",
        progress: 0,
      },
    ],
  },
  {
    title: "Interview",
    icon: FaUsers,
    color: "#7e57c2",
    items: [
      {
        name: "Placement Papers",
        icon: FaFileAlt,
        topics: "50 Papers",
        path: "/interview/placement-papers",
        progress: 0,
      },
      {
        name: "Group Discussion",
        icon: FaComments,
        topics: "25 Topics",
        path: "/interview/group-discussion",
        progress: 0,
      },
      {
        name: "HR Interview",
        icon: FaUserTie,
        topics: "30 Questions",
        path: "/interview/hr-interview",
        progress: 0,
      },
      {
        name: "Read more...",
        icon: FaFileAlt,
        topics: "20 Topics",
        path: "/interview/read-more",
        progress: 0,
      },
    ],
  },
  {
    title: "Engineering",
    icon: FaCogs,
    color: "#ef5350",
    items: [
      {
        name: "Mechanical Engineering",
        icon: FaCogs,
        topics: "45 Topics",
        path: "/engineering/mechanical-engineering",
        progress: 0,
      },
      {
        name: "Civil Engineering",
        icon: FaIndustry,
        topics: "40 Topics",
        path: "/engineering/civil-engineering",
        progress: 0,
      },
      {
        name: "ECE, EEE, CSE",
        icon: FaMicrochip,
        topics: "50 Topics",
        path: "/engineering/ece-eee-cse",
        progress: 0,
      },
      {
        name: "Chemical Engineering",
        icon: FaVial,
        topics: "35 Topics",
        path: "/engineering/chemical-engineering",
        progress: 0,
      },
    ],
  },
  {
    title: "Programming",
    icon: FaCode,
    color: "#26c6da",
    items: [
      {
        name: "C Programming",
        icon: FaCode,
        topics: "40 Topics",
        path: "/programming/c-programming",
        progress: 0,
      },
      {
        name: "C++ Programming",
        icon: FaCode,
        topics: "45 Topics",
        path: "/programming/cpp-programming",
        progress: 0,
      },
      {
        name: "C# Programming",
        icon: FaCode,
        topics: "35 Topics",
        path: "/programming/csharp-programming",
        progress: 0,
      },
      {
        name: "Java Programming",
        icon: FaJava,
        topics: "50 Topics",
        path: "/programming/java-programming",
        progress: 0,
      },
    ],
  },
  {
    title: "Online Tests",
    icon: FaLaptopCode,
    color: "#ba68c8",
    items: [
      {
        name: "Aptitude Test",
        icon: FaCalculator,
        topics: "30 Tests",
        path: "/online-tests/aptitude-test",
        progress: 0,
      },
      {
        name: "Verbal Ability Test",
        icon: FaBrain,
        topics: "25 Tests",
        path: "/online-tests/verbal-ability-test",
        progress: 0,
      },
      {
        name: "Logical Reasoning Test",
        icon: FaBrain,
        topics: "28 Tests",
        path: "/online-tests/logical-reasoning-test",
        progress: 0,
      },
      {
        name: "C Programming Test",
        icon: FaCode,
        topics: "20 Tests",
        path: "/online-tests/c-programming-test",
        progress: 0,
      },
      {
        name: "Read more...",
        icon: FaFileAlt,
        topics: "15 Tests",
        path: "/online-tests/read-more",
        progress: 0,
      },
    ],
  },
  {
    title: "Technical MCQs",
    icon: FaNetworkWired,
    color: "#d84315",
    items: [
      {
        name: "Networking Questions",
        icon: FaNetworkWired,
        topics: "100 Questions",
        path: "/technical-mcqs/networking-questions",
        progress: 0,
      },
      {
        name: "Database Questions",
        icon: FaDatabase,
        topics: "80 Questions",
        path: "/technical-mcqs/database-questions",
        progress: 0,
      },
      {
        name: "Basic Electronics",
        icon: FaMicrochip,
        topics: "90 Questions",
        path: "/technical-mcqs/basic-electronics",
        progress: 0,
      },
      {
        name: "Digital Electronics",
        icon: FaMicrochip,
        topics: "85 Questions",
        path: "/technical-mcqs/digital-electronics",
        progress: 0,
      },
      {
        name: "Read more...",
        icon: FaFileAlt,
        topics: "50 Questions",
        path: "/technical-mcqs/read-more",
        progress: 0,
      },
    ],
  },
  {
    title: "Technical Short Answers",
    icon: FaServer,
    color: "#2e7d32",
    items: [
      {
        name: "Software Testing",
        icon: FaLaptopCode,
        topics: "40 Topics",
        path: "/technical-short-answers/software-testing",
        progress: 0,
      },
      {
        name: "The C Language Basics",
        icon: FaCode,
        topics: "45 Topics",
        path: "/technical-short-answers/c-language-basics",
        progress: 0,
      },
      {
        name: "SQL Server",
        icon: FaDatabase,
        topics: "35 Topics",
        path: "/technical-short-answers/sql-server",
        progress: 0,
      },
      {
        name: "Networking",
        icon: FaNetworkWired,
        topics: "50 Topics",
        path: "/technical-short-answers/networking",
        progress: 0,
      },
      {
        name: "Read more...",
        icon: FaFileAlt,
        topics: "30 Topics",
        path: "/technical-short-answers/read-more",
        progress: 0,
      },
    ],
  },
  {
    title: "Medical Science",
    icon: FaMicroscope,
    color: "#9575cd",
    items: [
      {
        name: "Microbiology",
        icon: FaMicroscope,
        topics: "40 Topics",
        path: "/medical-science/microbiology",
        progress: 0,
      },
      {
        name: "Biochemistry",
        icon: FaDna,
        topics: "45 Topics",
        path: "/medical-science/biochemistry",
        progress: 0,
      },
      {
        name: "Biotechnology",
        icon: FaAtom,
        topics: "35 Topics",
        path: "/medical-science/biotechnology",
        progress: 0,
      },
      {
        name: "Biochemical Engineering",
        icon: FaFlaskAlt,
        topics: "30 Topics",
        path: "/medical-science/biochemical-engineering",
        progress: 0,
      },
    ],
  },
  {
    title: "Puzzles",
    icon: FaPuzzlePiece,
    color: "#ffb6c1",
    items: [
      {
        name: "Sudoku",
        icon: FaPuzzlePiece,
        topics: "50 Puzzles",
        path: "/puzzles/sudoku",
        progress: 0,
      },
      {
        name: "Number puzzles",
        icon: FaQuestionCircle,
        topics: "40 Puzzles",
        path: "/puzzles/number-puzzles",
        progress: 0,
      },
      {
        name: "Missing letters puzzles",
        icon: FaFont,
        topics: "30 Puzzles",
        path: "/puzzles/missing-letters-puzzles",
        progress: 0,
      },
      {
        name: "Logical puzzles",
        icon: FaBrain,
        topics: "45 Puzzles",
        path: "/puzzles/logical-puzzles",
        progress: 0,
      },
      {
        name: "Clock puzzles",
        icon: FaClock,
        topics: "25 Puzzles",
        path: "/puzzles/clock-puzzles",
        progress: 0,
      },
    ],
  },
];

export const categoryColors = {
  "General Aptitude": "#ef5350",
  "Verbal and Reasoning": "#7e57c2",
  "Current Affairs & GK": "#4caf50",
  Interview: "#7e57c2",
  Engineering: "#ef5350",
  Programming: "#26c6da",
  "Online Tests": "#ba68c8",
  "Technical MCQs": "#d84315",
  "Technical Short Answers": "#2e7d32",
  "Medical Science": "#9575cd",
  Puzzles: "#ffb6c1",
};
